/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import POJO.Application;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhin
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public Connection conn;
    public JPanel userProcessContainer;
    public ArrayList<Application> appList;
    public Application app;
    public SearchPanel(JPanel userProcessContainer, ArrayList<Application> applist, Connection conn) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.appList = applist;
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retreiveJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appTable = new javax.swing.JTable();
        searchTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        costJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        appNameJTextField = new javax.swing.JTextField();
        appDescJTextField = new javax.swing.JTextField();
        appReleaseDateJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();

        retreiveJButton.setText("FIND BY NAME");
        retreiveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retreiveJButtonActionPerformed(evt);
            }
        });

        appTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Application ID", "Name", "Description", "Release Date", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Retreive and Edit Apps");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Release Date :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Application Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Application Description :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Cost :");

        updateJButton.setText("UPDATE");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("SUBMIT");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setText("DELETE");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appNameJTextField)
                            .addComponent(appDescJTextField)
                            .addComponent(appReleaseDateJTextField)
                            .addComponent(costJTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retreiveJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteJButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateJButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitJButton)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retreiveJButton)
                    .addComponent(updateJButton)
                    .addComponent(deleteJButton))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(appNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(appDescJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(appReleaseDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(costJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitJButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retreiveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retreiveJButtonActionPerformed
        // TODO add your handling code here:
        appList.clear();
        PreparedStatement stmnt = null;

        try {
            stmnt = conn.prepareStatement("select * from searchApp(?)");
        } catch (SQLException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        ResultSet rs = null;

        try {
            if (searchTxtField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please do not leave field blank");
                return;
            }
            String search = searchTxtField.getText();
            stmnt.setString(1,search);
            rs = stmnt.executeQuery();
            if (!rs.isBeforeFirst()){
                JOptionPane.showMessageDialog(null,"Result not found !");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while(rs.next()){
                Application app = new Application();
                app.setApp_ID(rs.getInt("App_ID"));
                app.setApp_Name(rs.getString("App_Name"));
                app.setApp_Desc(rs.getString("App_Desc"));
                app.setRel_Date(rs.getString("Rel_Date"));
                app.setCost(rs.getString("Cost"));
                appList.add(app);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        populateTable(appList);
    }//GEN-LAST:event_retreiveJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = appTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table");
            return;
        }
        
        app = (Application) appTable.getValueAt(selectedRow,0);
        
        appNameJTextField.setText(app.getApp_Name());
        appDescJTextField.setText(app.getApp_Desc());
        appReleaseDateJTextField.setText(app.getRel_Date());
        costJTextField.setText(app.getCost());
        
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        appList.clear();
        if (appNameJTextField.getText().isEmpty() || appDescJTextField.getText().isEmpty() || appReleaseDateJTextField.getText().isEmpty() || costJTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please do not leave fields blank");
            return;
        }
        else{
            int id = app.getApp_ID();
            String name = appNameJTextField.getText();
            String desc = appDescJTextField.getText();
            String appRel = appReleaseDateJTextField.getText();
            String cost = costJTextField.getText();
            
            PreparedStatement stmnt=null;
            try {
                stmnt = conn.prepareStatement("EXEC data_update ?,?,?,?,?");
            } catch (SQLException ex) {
                Logger.getLogger(SearchPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                stmnt.setInt(1, id);
                stmnt.setString(2, name);
                stmnt.setString(3, desc);
                stmnt.setString(4, appRel);
                stmnt.setString(5, cost);
                
                stmnt.execute();
                
                stmnt.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(SearchPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        appDescJTextField.setText("");
        appNameJTextField.setText("");
        appReleaseDateJTextField.setText("");
        costJTextField.setText("");
        populateTable(appList);
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        appList.clear();
        int selectedRow = appTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        
        Application app = (Application) appTable.getValueAt(selectedRow,0);
        int app_id = app.getApp_ID();
        
        try {
            PreparedStatement stmnt = conn.prepareStatement("EXEC data_delete ?");
            stmnt.setInt(1,app_id);
            stmnt.execute();
            stmnt.close();
            
            JOptionPane.showMessageDialog(null,"Application deleted from the table");
            populateTable(appList);
        } catch (SQLException ex) {
            Logger.getLogger(SearchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteJButtonActionPerformed

    public void populateTable(ArrayList<Application> applist){
    
        DefaultTableModel dtm = (DefaultTableModel) appTable.getModel();
        dtm.setRowCount(0);
        
        for(Application app : applist){
        
            Object[] row = new Object [5];
            row [0] = app;
            row [1] = app.getApp_Name();
            row [2] = app.getApp_Desc();
            row [3] = app.getRel_Date();
            row [4] = app.getCost();
            dtm.addRow(row);
 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appDescJTextField;
    private javax.swing.JTextField appNameJTextField;
    private javax.swing.JTextField appReleaseDateJTextField;
    private javax.swing.JTable appTable;
    private javax.swing.JTextField costJTextField;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retreiveJButton;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
