/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGO.InventoryRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Organization.NGOInventoryOrg;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.Resources.Resource;
import Business.WorkQueue.NGOResourceWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhin
 */

public class NGOInventoryWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NGOInventoryOrg organization;
    private OrganizationDirectory organizationDir;
    private NGOEnterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public NGOInventoryWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, 
            Enterprise enterprise, EcoSystem business) {
        
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = (NGOInventoryOrg) organization;
        this.organizationDir = enterprise.getOrganizationDirectory();
        this.enterprise = (NGOEnterprise) enterprise;
        this.userAccount = account;
        this.business = business;

        valueLabel.setText(enterprise.getName());
        populateRequestTable();
        popResourceCombo();
    }
    
    public void popResourceCombo(){
        resourceComboBox.removeAllItems();
        for (Resource.ResourceType type : Resource.ResourceType.values()){
            resourceComboBox.addItem(type);
        }
    }
    
    
    public void populateProviderResourceTable(Resource.ResourceType type){
        
        DefaultTableModel model = (DefaultTableModel)resourceDirectoryJTable.getModel();
        int count=0;
        model.setRowCount(0);
                
        for (Resource r : organization.getResourcesReceivedDir().getResourceList()){
           
            if (r.getResourceType().equalsIgnoreCase(type.getValue())){
            
                Object[] row = new Object[4];            
                row[0] = r;
                row[1] = r.getTotalDonatedToNGO();
                row[2] = r.getUnitPrice();
                row[3] = r.getTotalDonatedToNGO() * r.getUnitPrice();
                model.addRow(row);
                count += r.getTotalDonatedToNGO();
            
            }
        }
              
      lbltotalResources.setText(String.valueOf(count));
      
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            
            if (request instanceof NGOResourceWorkRequest){
                
                NGOResourceWorkRequest req = (NGOResourceWorkRequest) request;
                
                Object[] row = new Object[5];
                row[0] = req.getResourceName();
                row[1] = req;
                row[2] = req.getSender().getEmployee().getName();
                row[3] = req.getReceiver() == null ? null : req.getReceiver().getEmployee().getName();
                row[4] = req.getStatus();
                model.addRow(row);
                
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestResourceJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        resourceDirectoryJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbltotalResources = new javax.swing.JLabel();
        removeResource = new javax.swing.JButton();
        resourceComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        notifyGovtJButton = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 185, 255));

        requestResourceJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        requestResourceJButton.setText("Request Resource >>");
        requestResourceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestResourceJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("NGO Inventory Work Area");

        refreshJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource Requested", "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        resourceDirectoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource Name", "Resource Quantity", "Resource Unit Price", "Resource Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resourceDirectoryJTable);
        if (resourceDirectoryJTable.getColumnModel().getColumnCount() > 0) {
            resourceDirectoryJTable.getColumnModel().getColumn(0).setResizable(false);
            resourceDirectoryJTable.getColumnModel().getColumn(1).setResizable(false);
            resourceDirectoryJTable.getColumnModel().getColumn(2).setResizable(false);
            resourceDirectoryJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Total Resource Units = ");

        lbltotalResources.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lbltotalResources.setText("<Value>");

        removeResource.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        removeResource.setText("Remove Resource");
        removeResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeResourceActionPerformed(evt);
            }
        });

        resourceComboBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        resourceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        resourceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("Resource Type : ");

        notifyGovtJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        notifyGovtJButton.setText("Notify Government >>");
        notifyGovtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyGovtJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Resource Inventory List :");

        enterpriseLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        enterpriseLabel2.setText("Resource Request List :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(resourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(requestResourceJButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbltotalResources)
                                            .addGap(38, 38, 38)
                                            .addComponent(removeResource)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(notifyGovtJButton)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshJButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbltotalResources)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removeResource)
                        .addComponent(notifyGovtJButton)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestResourceJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestResourceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestResourceJButtonActionPerformed
       
        NGORequestResourceJPanel nrjp = new NGORequestResourceJPanel(userProcessContainer,userAccount,
        enterprise,organization,business);
        userProcessContainer.add("NGORequestResourceJPanel", nrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_requestResourceJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void removeResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeResourceActionPerformed
        // TODO add your handling code here:
        int getselectedResource = resourceDirectoryJTable.getSelectedRow();
        Resource.ResourceType type = (Resource.ResourceType) resourceComboBox.getSelectedItem();
        
        if (getselectedResource<0){
            JOptionPane.showMessageDialog(null,"Please select a row !");
            return;
        }
        
        Resource r = (Resource) resourceDirectoryJTable.getValueAt(getselectedResource,0);
        
        for (Resource res : organization.getResourcesReceivedDir().getResourceList()){
            if ((res.getResourceType().equalsIgnoreCase(type.getValue())) && (res.equals(r))){
                organization.getResourcesReceivedDir().removeResource(res);
                break;
            }
        }
        
        populateProviderResourceTable(type);
    }//GEN-LAST:event_removeResourceActionPerformed

    private void resourceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceComboBoxActionPerformed
        // TODO add your handling code here:
        Resource.ResourceType type = (Resource.ResourceType) resourceComboBox.getSelectedItem();
        if(type !=null){
            populateProviderResourceTable(type);
        }
    }//GEN-LAST:event_resourceComboBoxActionPerformed

    private void notifyGovtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyGovtJButtonActionPerformed
        // TODO add your handling code here:
        int getselectedResource = resourceDirectoryJTable.getSelectedRow();
        
        if (getselectedResource < 0){
            JOptionPane.showMessageDialog(null, "Please select a row ");
            return;
        }
        
        Resource donatedResource = (Resource) resourceDirectoryJTable.getValueAt(getselectedResource,0);
        
        NotifyGovernmentJPanel ngjp = new NotifyGovernmentJPanel(userProcessContainer, userAccount,
                enterprise, business, donatedResource);
        
        userProcessContainer.add("NotifyGovernmentJPanel", ngjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_notifyGovtJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotalResources;
    private javax.swing.JButton notifyGovtJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeResource;
    private javax.swing.JButton requestResourceJButton;
    private javax.swing.JComboBox resourceComboBox;
    private javax.swing.JTable resourceDirectoryJTable;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
