/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGO.InventoryRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Resources.BookResource;
import Business.Resources.ClothingResource;
import Business.UserAccount.UserAccount;
import Business.Resources.Resource;
import Business.WorkQueue.NotifyGovernmentWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author abhin
 */
public class NotifyGovernmentJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Resource donatedResource;
    EcoSystem business;
    UserAccount account;
    
    int donatedResourceValue;
    
    public NotifyGovernmentJPanel(JPanel userProcessContainer,UserAccount userAccount, 
            Enterprise enterprise, EcoSystem business,Resource resource) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.donatedResource = resource;
        this.business = business;
        this.account = userAccount;
        
        settext();
    }
    
    public Network findNetwork(){
        for (Network n : business.getNetworkList()){
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                        if (account.equals(ua)){
                            return n;
                        }
                    }
                }
            }
        }
        return null;
    }
    
    public void settext(){
        
        if (donatedResource.getResourceType().equals(Resource.ResourceType.Book.getValue())){
            
            BookResource br = (BookResource) donatedResource;
            resourceTypeJTextField.setText(Resource.ResourceType.Book.getValue());
            resourceNameJTextField.setText(br.getBookName());
            resourceQuantityJTextField.setText(String.valueOf(br.getTotalDonatedToNGO()));
            
            donatedResourceValue = br.getTotalDonatedToNGO() * br.getUnitPrice();
            
            donResValueJTextField.setText(String.valueOf(donatedResourceValue));
            taxBenefitValueJTextField.setText(String.valueOf(donatedResourceValue * br.getBookTaxbenefitPercent()));
        }
        
        else if (donatedResource.getResourceType().equals(Resource.ResourceType.Clothing.getValue())){
            ClothingResource br = (ClothingResource) donatedResource;
            resourceTypeJTextField.setText(Resource.ResourceType.Clothing.getValue());
            resourceNameJTextField.setText(br.getClothingItemName());
            resourceQuantityJTextField.setText(String.valueOf(br.getTotalDonatedToNGO()));
            
            donatedResourceValue = br.getTotalDonatedToNGO() * br.getUnitPrice();
            
            donResValueJTextField.setText(String.valueOf(donatedResourceValue));
            taxBenefitValueJTextField.setText(String.valueOf(donatedResourceValue * br.getClothesTaxBenefitPercent()));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        donResValueJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resourceQuantityJTextField = new javax.swing.JTextField();
        resourceNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        notifyGovernmentJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        taxBenefitValueJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        resourceTypeJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 185, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Government Notification Work Area");

        donResValueJTextField.setEditable(false);
        donResValueJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donResValueJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("Resource Quantity :");

        resourceQuantityJTextField.setEditable(false);
        resourceQuantityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceQuantityJTextFieldActionPerformed(evt);
            }
        });

        resourceNameJTextField.setEditable(false);
        resourceNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Resource Name :");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("Donated Resource Value :");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel6.setText("Donated Resource Information:");

        notifyGovernmentJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        notifyGovernmentJButton.setText("Notify");
        notifyGovernmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyGovernmentJButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setText("Expected Tax Benefit Value :");

        taxBenefitValueJTextField.setEditable(false);
        taxBenefitValueJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxBenefitValueJTextFieldActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        resourceTypeJTextField.setEditable(false);
        resourceTypeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceTypeJTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("Resource Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(resourceTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resourceNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resourceQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(donResValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(notifyGovernmentJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(taxBenefitValueJTextField)))))
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(resourceTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resourceNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resourceQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(donResValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(taxBenefitValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(notifyGovernmentJButton)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donResValueJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donResValueJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donResValueJTextFieldActionPerformed

    private void resourceQuantityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceQuantityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceQuantityJTextFieldActionPerformed

    private void resourceNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceNameJTextFieldActionPerformed

    private void notifyGovernmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyGovernmentJButtonActionPerformed
        // TODO add your handling code here:
        GovernmentEnterprise org = null; //Enterprise since Govt has only admin organization
        NotifyGovernmentWorkRequest request=null;
        
        if (donatedResource.getResourceType().equals(Resource.ResourceType.Book.getValue())){
            BookResource br = (BookResource) donatedResource;
            request = new NotifyGovernmentWorkRequest(br);
            
            request.setTaxBenefitValue(donatedResourceValue * br.getBookTaxbenefitPercent());
            request.setMessage("Approval for " + br.getBookName() + "sent successfully");
        }
        else if (donatedResource.getResourceType().equals(Resource.ResourceType.Clothing.getValue())){
            ClothingResource cr = (ClothingResource) donatedResource;
            request = new NotifyGovernmentWorkRequest(cr);
            
            request.setTaxBenefitValue(donatedResourceValue * cr.getClothesTaxBenefitPercent());
            request.setMessage("Approval for " + cr.getClothingItemName() + "sent successfully");
        }
        
        
        Network n = findNetwork();
            
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                
                if (e instanceof GovernmentEnterprise){
                    org = (GovernmentEnterprise) e ;
                    break;
                }
                
            }
        
        
        
        request.setDonatedResourceValue(donatedResourceValue);
        request.setSender(account);
        request.setStatus("Government Notification Sent");

        
        if (org != null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        
        
        JOptionPane.showMessageDialog(null,"Resource Notification sent to local Government!");
                        
    }//GEN-LAST:event_notifyGovernmentJButtonActionPerformed

    private void taxBenefitValueJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxBenefitValueJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxBenefitValueJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void resourceTypeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceTypeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceTypeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField donResValueJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton notifyGovernmentJButton;
    private javax.swing.JTextField resourceNameJTextField;
    private javax.swing.JTextField resourceQuantityJTextField;
    private javax.swing.JTextField resourceTypeJTextField;
    private javax.swing.JTextField taxBenefitValueJTextField;
    // End of variables declaration//GEN-END:variables
}
