/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClothingEnterprise.Provider;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClothingProviderOrg;
import Business.Organization.Organization;
import Business.Providers.Provider;
import Business.Resources.Resource;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderTaxBenefitWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhin
 */
public class ClothingProviderWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ClothingProviderOrg organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private ArrayList<ClothingProviderOrg> clothingProviderOrgList;
    private Provider provider;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ClothingProviderWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, 
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = (ClothingProviderOrg) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        
        clothingProviderOrgList = new ArrayList<>();
        getClothingProviderOrgs();
        
        this.provider = getLoggedInProvider();
        
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
        populateDonatedResourceTable();
    }
    
    public void getClothingProviderOrgs(){
        
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (o instanceof ClothingProviderOrg){
                ClothingProviderOrg org = (ClothingProviderOrg) o;
                clothingProviderOrgList.add(org);
            }
        }
        
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
    public Provider getLoggedInProvider(){
        
      Provider mfg=null;
      
        for (ClothingProviderOrg mo : clothingProviderOrgList){
            
            for (Provider m : mo.getClothingProviderDirectory().getProviderDirectory()){
                
                if (m.getName().equalsIgnoreCase(userAccount.getEmployee().getName())){ //Employee name must be same as mfg name.
                    mfg = m;
                    break;
                }
            }
        }
        return mfg;
    }
    
    public void populateDonatedResourceTable(){
        DefaultTableModel model = (DefaultTableModel) resourceDirectoryJTable.getModel();
        model.setRowCount(0);
        
        for (Resource r : provider.getDonatedResources().getResourceList()){
            Object row[] = new Object[4];
            row[0] = r;
            row[1] = r.getTotalDonatedToSystem();
            row[2] = r.getUnitPrice();
            row[3] = r.getUnitPrice() * r.getTotalDonatedToSystem();
            model.addRow(row);
        }
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTaxJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        manageDonationsJButton = new javax.swing.JButton();
        manageSalesFiguresJButton = new javax.swing.JButton();
        manageResourceJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resourceDirectoryJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 229, 150));

        enterpriseLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Clothing Provider Work Request Area");

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        requestTaxJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        requestTaxJButton.setText("Request Tax Benefit >>");
        requestTaxJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTaxJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        manageDonationsJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        manageDonationsJButton.setText("Manage Donations >>");
        manageDonationsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDonationsJButtonActionPerformed(evt);
            }
        });

        manageSalesFiguresJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        manageSalesFiguresJButton.setText("Manage Sales Figures >>");
        manageSalesFiguresJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSalesFiguresJButtonActionPerformed(evt);
            }
        });

        manageResourceJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        manageResourceJButton.setText("Manage Resources >>");
        manageResourceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageResourceJButtonActionPerformed(evt);
            }
        });

        resourceDirectoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource Name", "Resource Quantity", "Resource Unit Price", "Resource Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resourceDirectoryJTable);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Donated Resource History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshJButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageResourceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageSalesFiguresJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(239, 239, 239)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(requestTaxJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageDonationsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageResourceJButton)
                    .addComponent(manageDonationsJButton))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageSalesFiguresJButton)
                    .addComponent(requestTaxJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTaxJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTaxJButtonActionPerformed

        int selectedRow = resourceDirectoryJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row!");
            return;
        }
        
        Resource resource = (Resource) resourceDirectoryJTable.getValueAt(selectedRow,0);

        ClothingProviderTaxRequestJPanel clothingProviderTaxRequestJPanel = new ClothingProviderTaxRequestJPanel(userProcessContainer, userAccount, 
            enterprise, business, resource,provider);
        userProcessContainer.add("ClothingProviderTaxRequestJPanel", clothingProviderTaxRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestTaxJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void manageDonationsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDonationsJButtonActionPerformed
        // TODO add your handling code here:
        ManageClothingDonationsJPanel mvjp = new ManageClothingDonationsJPanel(userProcessContainer,userAccount, 
            organization, enterprise, business, provider);
        userProcessContainer.add ("ManageClothingDonationsJPanel", mvjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDonationsJButtonActionPerformed

    private void manageSalesFiguresJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSalesFiguresJButtonActionPerformed
        // TODO add your handling code here:
        ClothingProviderSalesFiguresJPanel cpsjp = new ClothingProviderSalesFiguresJPanel(userProcessContainer,userAccount, 
            organization, enterprise, business, provider);
        userProcessContainer.add("ClothingProviderSalesFiguresJPanel",cpsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSalesFiguresJButtonActionPerformed

    private void manageResourceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageResourceJButtonActionPerformed
        // TODO add your handling code here:
        ManageClothingResourceJPanel mbrjp = new ManageClothingResourceJPanel(userProcessContainer,userAccount, 
            organization, enterprise, business, provider);
        userProcessContainer.add("ManageClothingResourceJPanel",mbrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageResourceJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton manageDonationsJButton;
    private javax.swing.JButton manageResourceJButton;
    private javax.swing.JButton manageSalesFiguresJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton requestTaxJButton;
    private javax.swing.JTable resourceDirectoryJTable;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}