/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BookEnterprise.Provider;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Providers.Provider;
import Business.Resources.BookResource;
import Business.UserAccount.UserAccount;
import Business.Resources.Resource;
import Business.WorkQueue.ProviderTaxBenefitWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author abhin
 */
public class BookProviderTaxRequestJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    BookResource bookResource;
    EcoSystem business;
    UserAccount account;
    Provider provider;
    
    public BookProviderTaxRequestJPanel(JPanel userProcessContainer,UserAccount userAccount, 
            Enterprise enterprise, EcoSystem business,Resource resource, Provider provider) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.bookResource = (BookResource) resource;
        this.business = business;
        this.account = userAccount;
        this.provider = provider;
        
        settext();
    }
    
    public Network findNetwork(){
        for (Network n : business.getNetworkList()){
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                        if (account.equals(ua)){
                            return n;
                        }
                    }
                }
            }
        }
        return null;
    }
    
    public void settext(){
        resourceNameJTextField.setText(bookResource.getBookName());
        resourceQuantityJTextField.setText(String.valueOf(bookResource.getTotalDonatedToSystem()));
        int donatedResourceValue = bookResource.getTotalDonatedToSystem() * bookResource.getUnitPrice();
        donResValueJTextField.setText(String.valueOf(donatedResourceValue));
        taxBenefitValueJTextField.setText(String.valueOf(donatedResourceValue * bookResource.getBookTaxbenefitPercent()));
    }
    
    public void getProvider(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        donResValueJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resourceQuantityJTextField = new javax.swing.JTextField();
        resourceNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        requestBenefitJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        taxBenefitValueJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(192, 223, 217));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Book Provider Tax Request");

        donResValueJTextField.setEditable(false);
        donResValueJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        donResValueJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donResValueJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("Resource Quantity :");

        resourceQuantityJTextField.setEditable(false);
        resourceQuantityJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        resourceQuantityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceQuantityJTextFieldActionPerformed(evt);
            }
        });

        resourceNameJTextField.setEditable(false);
        resourceNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        resourceNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Resource Name :");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("Donated Resource Value :");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setText("Donated Resource Information:");

        requestBenefitJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        requestBenefitJButton.setText("Request for Benefit");
        requestBenefitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBenefitJButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setText("Expected Tax Benefit Value :");

        taxBenefitValueJTextField.setEditable(false);
        taxBenefitValueJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        taxBenefitValueJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxBenefitValueJTextFieldActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resourceNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resourceQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donResValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(taxBenefitValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(requestBenefitJButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(resourceNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resourceQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(donResValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(taxBenefitValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestBenefitJButton)
                    .addComponent(backJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donResValueJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donResValueJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donResValueJTextFieldActionPerformed

    private void resourceQuantityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceQuantityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceQuantityJTextFieldActionPerformed

    private void resourceNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceNameJTextFieldActionPerformed

    private void requestBenefitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBenefitJButtonActionPerformed
        // TODO add your handling code here:
        GovernmentEnterprise org = null; //Enterprise since Govt has only admin organization 
        
        ProviderTaxBenefitWorkRequest request = new ProviderTaxBenefitWorkRequest(bookResource);
        request.setProvider(provider);
        
       Network n = findNetwork();
            
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                
                if (e instanceof GovernmentEnterprise){
                    org = (GovernmentEnterprise) e ;
                    break;
                }
                
            }
         
        
        request.setSender(account);
        request.setStatus("Sent to Government for Approval");
        request.setMessage("Approval for " + bookResource.getBookName());
        
        if (org != null){            
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }

        JOptionPane.showMessageDialog(null,"Request for benefit sent to local Government!");
                        
    }//GEN-LAST:event_requestBenefitJButtonActionPerformed

    private void taxBenefitValueJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxBenefitValueJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxBenefitValueJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField donResValueJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton requestBenefitJButton;
    private javax.swing.JTextField resourceNameJTextField;
    private javax.swing.JTextField resourceQuantityJTextField;
    private javax.swing.JTextField taxBenefitValueJTextField;
    // End of variables declaration//GEN-END:variables
}
