/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentEnterprise.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.BookProviderOrg;
import Business.Organization.GovernmentAdminOrg;
import Business.Organization.Organization;
import Business.Providers.Provider;
import Business.Resources.BookResource;
import Business.Resources.Resource;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderTaxBenefitWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhin
 */
public class GovtAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private GovernmentAdminOrg organization;
    private GovernmentEnterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    private Provider provider;
    
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public GovtAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, 
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = (GovernmentAdminOrg) organization;
        this.enterprise = (GovernmentEnterprise) enterprise;
        this.userAccount = account;
        this.business = business;
        
                        
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
        
        txtBookTaxBenefitPercent.setEnabled(false);
        btnSetPercentBook.setEnabled(false);
        btnModifyPercentBook.setEnabled(true);
        
        txtClothesTaxBenefitPercent.setEnabled(false);
        btnSetPercentClothes.setEnabled(false);
        btnModifyPercentClothes.setEnabled(true);
        
        txtBookTaxBenefitPercent.setText(String.valueOf(business.getBtb().getBooktaxBenefitPercentage() * 100));
        txtClothesTaxBenefitPercent.setText(String.valueOf(business.getCtb().getClothesTaxBenefitPercentage() * 100));
        
    }    
    
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            
            if (request instanceof ProviderTaxBenefitWorkRequest){
                
                ProviderTaxBenefitWorkRequest req = (ProviderTaxBenefitWorkRequest) request;
                                    
                    Object[] row = new Object[6];
                    row[0] = req;
                    row[1] = req.getDonatedResource().getTotalDonatedToSystem();
                    row[2] = req.getDonatedResource().getUnitPrice() * req.getDonatedResource().getTotalDonatedToSystem();
                    row[3] = req.getSender().getEmployee().getName();
                    row[4] = req.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                    row[5] = req.getStatus();

                    model.addRow(row);
            }
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        manageTaxApprovalJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBookTaxBenefitPercent = new javax.swing.JTextField();
        btnModifyPercentBook = new javax.swing.JButton();
        btnSetPercentBook = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        txtClothesTaxBenefitPercent = new javax.swing.JTextField();
        btnModifyPercentClothes = new javax.swing.JButton();
        btnSetPercentClothes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnMonitorTaxBenefit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 218, 185));

        enterpriseLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Government Admin Work Request Area");

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource Name", "Resource Quantity", "Donated Resource Value", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        refreshJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        manageTaxApprovalJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        manageTaxApprovalJButton.setText("Manage Tax Approvals >>");
        manageTaxApprovalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTaxApprovalJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Provider Tax Benefit Requests");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Current Tax Benefit %  for Books =");

        btnModifyPercentBook.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        btnModifyPercentBook.setText("Modify");
        btnModifyPercentBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyPercentBookActionPerformed(evt);
            }
        });

        btnSetPercentBook.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        btnSetPercentBook.setText("Set");
        btnSetPercentBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetPercentBookActionPerformed(evt);
            }
        });

        assignJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        btnModifyPercentClothes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        btnModifyPercentClothes.setText("Modify");
        btnModifyPercentClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyPercentClothesActionPerformed(evt);
            }
        });

        btnSetPercentClothes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        btnSetPercentClothes.setText("Set");
        btnSetPercentClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetPercentClothesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Current Tax Benefit % for Clothes =");

        btnMonitorTaxBenefit.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        btnMonitorTaxBenefit.setText("Monitor Tax Benefit Effectiveness >>");
        btnMonitorTaxBenefit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorTaxBenefitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshJButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnModifyPercentBook)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSetPercentBook, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtBookTaxBenefitPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(assignJButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(manageTaxApprovalJButton))
                                    .addComponent(btnMonitorTaxBenefit, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnModifyPercentClothes)
                                    .addGap(14, 14, 14)
                                    .addComponent(btnSetPercentClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtClothesTaxBenefitPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtBookTaxBenefitPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSetPercentBook)
                            .addComponent(btnModifyPercentBook))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtClothesTaxBenefitPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assignJButton)
                            .addComponent(manageTaxApprovalJButton))
                        .addGap(18, 18, 18)
                        .addComponent(btnMonitorTaxBenefit)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModifyPercentClothes)
                    .addComponent(btnSetPercentClothes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void manageTaxApprovalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTaxApprovalJButtonActionPerformed
        // TODO add your handling code here:
        int getselectedRow = workRequestJTable.getSelectedRow();
        
        if (getselectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        
        ProviderTaxBenefitWorkRequest request = (ProviderTaxBenefitWorkRequest) workRequestJTable.getValueAt(getselectedRow, 0);
        
        ManageTaxBenefitApprovalJPanel mtbajp = new ManageTaxBenefitApprovalJPanel(userProcessContainer,userAccount, 
            organization, enterprise, business,request);
        userProcessContainer.add ("ManageTaxBenefitApprovalJPanel", mtbajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageTaxApprovalJButtonActionPerformed

    private void btnModifyPercentBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyPercentBookActionPerformed
        // TODO add your handling code here:
        txtBookTaxBenefitPercent.setEnabled(true);
        btnSetPercentBook.setEnabled(true);
        btnModifyPercentBook.setEnabled(false);
    }//GEN-LAST:event_btnModifyPercentBookActionPerformed

    private void btnSetPercentBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetPercentBookActionPerformed
        // TODO add your handling code here:
        if (!txtBookTaxBenefitPercent.getText().isEmpty()){
            double val = Double.parseDouble(txtBookTaxBenefitPercent.getText());
            if (val < 0){
                JOptionPane.showMessageDialog(null,"Percentage cannot be negative","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            business.getBtb().setBooktaxBenefitPercentage(val/100);
            enterprise.getBookTaxPercentages().add(val/100);
            txtBookTaxBenefitPercent.setEnabled(false);
            btnModifyPercentBook.setEnabled(true);
            btnSetPercentBook.setEnabled(false);
            
            JOptionPane.showMessageDialog(null,"Tax Benefit Percentage Changed!");
        }
        else 
            JOptionPane.showMessageDialog(null,"Please do not leave field blank","Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnSetPercentBookActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }

        ProviderTaxBenefitWorkRequest request = (ProviderTaxBenefitWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        if (request.getStatus().equalsIgnoreCase("Pending")){
            JOptionPane.showMessageDialog(null,"Request has already been assigned");
            return;
        }
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateRequestTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnModifyPercentClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyPercentClothesActionPerformed
        // TODO add your handling code here:
        txtClothesTaxBenefitPercent.setEnabled(true);
        btnSetPercentClothes.setEnabled(true);
        btnModifyPercentClothes.setEnabled(false);
    }//GEN-LAST:event_btnModifyPercentClothesActionPerformed

    private void btnSetPercentClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetPercentClothesActionPerformed
        // TODO add your handling code here:
        if (!txtClothesTaxBenefitPercent.getText().isEmpty()){
            double val = Double.parseDouble(txtClothesTaxBenefitPercent.getText());
            if (val < 0){
                JOptionPane.showMessageDialog(null,"Percentage cannot be negative","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            business.getCtb().setClothesTaxBenefitPercentage(val/100);
            enterprise.getClothingTaxPercentages().add(val/100);
            txtClothesTaxBenefitPercent.setEnabled(false);
            btnModifyPercentClothes.setEnabled(true);
            btnSetPercentClothes.setEnabled(false);
            
            JOptionPane.showMessageDialog(null,"Tax Benefit Percentage Changed!");
        }
        else 
            JOptionPane.showMessageDialog(null,"Please do not leave field blank","Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnSetPercentClothesActionPerformed

    private void btnMonitorTaxBenefitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorTaxBenefitActionPerformed
        // TODO add your handling code here:
        MonitorTaxBenefitJPanel mtbjp = new MonitorTaxBenefitJPanel(userProcessContainer,userAccount,organization, 
            enterprise,business);
        
        userProcessContainer.add("MonitorTaxBenefitJPanel",mtbjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMonitorTaxBenefitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnModifyPercentBook;
    private javax.swing.JButton btnModifyPercentClothes;
    private javax.swing.JButton btnMonitorTaxBenefit;
    private javax.swing.JButton btnSetPercentBook;
    private javax.swing.JButton btnSetPercentClothes;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageTaxApprovalJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField txtBookTaxBenefitPercent;
    private javax.swing.JTextField txtClothesTaxBenefitPercent;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}